kafka:
  topic: json
  bootstrap-server-url: localhost
  bootstrap-server-port: 9092
jdbc:
  driver-class: "org.postgresql.Driver"
  jdbc-url: "jdbc:postgresql://localhost:5432/metrics"
  user: user
  password: 123