# The workflow to release docker container for consumer.
# It triggers after pushing changes either in commons or in consumer
name: Master checks for Consumer

on:
  push:
    branches:
      - main
    paths:
      - 'metric-commons/**'
      - 'metric-consumer/**'

jobs:
  build:
    name: Build Consumer
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Check before
        run: |
          pwd
          ls -lt
          cat  metric-consumer/src/main/resources/env/testing.yml

      - name: Substitute variable
        uses: microsoft/variable-substitution@v1
        with:
          files: ' metric-consumer/src/main/resources/env/testing.yml'
        env:
          jdbc.jdbc-url: ${{secrets.DB_URL}}
          jdbc.user: ${{secrets.DB_USER}}
          jdbc.password: ${{secrets.DB_PASSWORD}}
          kafka.certstore-password: ${{secrets.KAFKA_CERT_PASSWORD}}
          kafka.bootstrap-server-url: ${{secrets.KAFKA_HOST}}
          kafka.bootstrap-server-port: ${{secrets.KAFKA_PORT}}

      - name: Check after
        run: |
          cat  metric-consumer/src/main/resources/env/testing.yml

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Gradle
        run: ./gradlew metric-consumer:build