# The workflow to release docker container for producer.
# It triggers after pushing changes either in commons or in producer
name: Master checks for Producer

on:
  push:
    branches:
      - main
    paths:
      - 'metric-commons/**'
      - 'metric-producer/**'

jobs:
  build:
    name: Build Producer
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Build certstore
        working-directory: ./metric-producer
        run: |
          cd src/main/resources
          echo '${{secrets.SERVICE_KEY}}' > service.key
          echo '${{secrets.SERVICE_CERT}}' > service.cert
          echo '${{secrets.CA_PEM}}' > ca.pem
          ls -lt
          cat ca.pem
          openssl pkcs12 -export -inkey service.key -in service.cert -out client.keystore.p12 -name service_key -pass pass:'${{secrets.KAFKA_CERT_PASSWORD}}'
          keytool -import -file ca.pem -alias CA -keystore client.truststore.jks
          ls -lt

      - name: Substitute variable
        uses: microsoft/variable-substitution@v1
        with:
          files: 'metric-producer/src/main/resources/env/testing.yml'
        env:
          kafka.certstore-password: ${{secrets.KAFKA_CERT_PASSWORD}}
          kafka.bootstrap-server-url: ${{secrets.KAFKA_HOST}}
          kafka.bootstrap-server-port: ${{secrets.KAFKA_PORT}}
          kafka.schema-registry-url: ${{secrets.KAFKA_SCHEMA_REGISTRY_URL}}
          kafka.schema-registry-basic-auth: ${{secrets.KAFKA_SCHEMA_REGISTRY_AUTH}}

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Gradle
        run: ./gradlew metric-producer:build

      - name: Publish to Docker Registry
        working-directory: ./metric-producer
        run: |
          docker image build -t metric-producer .
          echo '${{secrets.DOCKER_PRIVATE_PASSWORD}}' | docker login --username=yushkevich --password-stdin
          docker tag metric-producer yushkevich/metric-producer:latest
          docker push yushkevich/metric-producer:latest