# The workflow to release docker container for consumer.
# It triggers after pushing changes either in commons or in consumer
name: Master checks for Consumer

on:
  push:
    branches:
      - main
    paths:
      - 'metric-commons/**'
      - 'metric-consumer/**'

jobs:
  build:
    name: Build Consumer
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Substitute variable
        uses: microsoft/variable-substitution@v1
        run: |
          pwd
#        with:
#          files: ''

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Gradle
        run: ./gradlew metric-consumer:build