# The workflow to migrate changes for Postgres DB.
# It triggers after pushing changes in scripts/migrations
name: Master checks for DB

on:
  push:
    branches:
      - main
    paths:
      - 'scripts/migrations/**'

jobs:
  build:
    name: Migrate Database
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Download flyway
        run: |
          FLYWAY_VERSION=7.3.1
          echo $FLYWAY_VERSION
          curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/$FLYWAY_VERSION/flyway-commandline-$FLYWAY_VERSION.tar.gz \
          -o flyway-commandline-$FLYWAY_VERSION.tar.gz && tar -xzf flyway-commandline-$FLYWAY_VERSION.tar.gz \
          --strip-components=1 && rm flyway-commandline-$FLYWAY_VERSION.tar.gz

